name = "nearby"
compatibility_date = "2025-06-25"

[build]
command = "npm run build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[context.production]
[context.production.env]
NODE_VERSION = "20"
